### ISSUE TITLE
FIx editor config max_line_length

### ISSUE THREAD

**Issue by denisSurkov** [fandsdev/django#313]
@f213 , почему в .[editorconfig max_line_length стоит 0?](https://github.com/fandsdev/django/blob/58b698c5f3a02deeca9571994320ed97a0836886/%7B%7Bcookiecutter.project_slug%7D%7D/.editorconfig#L4)

Из-за этого в IDE появляется отвратительная линия в начале строк. Конечно, её можно отключить, но она визуально показывает ограничение.

Пример линии, как сейчас настроен editorconfig:
![image](https://user-images.githubusercontent.com/34986204/132103927-db0aee1a-687a-4ade-862b-711c6d47cc0c.png)

Пример линии, как должно быть -- она сбоку:
(ограничение 160 символов для .py файлов)
![image](https://user-images.githubusercontent.com/34986204/132103956-cf99e526-1789-46e4-8bae-807be9f1d3c8.png)

**Comment by f213** [comment]
Идея была в том, чтобы отключить совсем ограничение на ширину строки, т.к. я считаю её неважной. В стандарте editorconfig сейчас [написано](https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties#supported-by-a-limited-number-of-editors), что для этих целей надо ставить значение `off`. Попробуешь?

**Comment by denisSurkov** [comment]
Да, попробовал.

Все ок, линия убралась. Так намного лучше
