### ISSUE TITLE
Добавить post_act в BaseService

### ISSUE THREAD

**Issue by denisSurkov** [fandsdev/django#519]
Иногда в сервисах нужно использовать ```transaction.atomic```

При этом некоторые действия можно будет сделать только после того, как будет выполнена основная часть сервиса.

К примеру, есть задача по загрузке пользователей из другой системы. Сначала в теле транзакции мы сохраняем все важные данные, а после того, как все сохранили, отправляем фоновую задачку на скачивание аватарки.

Если вызывать таску внутри тела транзакции, то таски будут отваливаться, потому что юзера еще нет в системе (или вообще не будет, потому что транзакция не прошла).

Я предлагаю два варианта:

1. Сделать отдельный сервис BaseTransactionService

```python
class BaseTransactionService(BaseService):
    def act(self):
        with transaction.atomic():
            result = self.transactional_act()
        self.apply_after_transaction()
        return result

    @abc.abstractmethod
    def transactional_act(self):
        ...

    def apply_after_transaction(self):
        ...
```

2. Добавить в базовый сервис post_act

```python
...
    def __call__(self) -> None:
        self.validate()
        result = self.act()
        self.post_act()
        return result
...
```
На мой взгляд, первый способ лучше. По названию метода сразу понятно, что действие будет внутри транзакции. Но тут хочу мнения со стороны.

**Comment by denisSurkov** [comment]
@nvo87 , @f213 , @kazqvaizer , @justaregularacc , поделитесь мнением, пожалуйста.

Если кого забыл спросить, тэгните, пожалуйста.

**Comment by f213** [comment]
Мне оба варианта не нравятся — кажется мы не пишем настолько много сервисов, чтобы экономить строчку кода в ущерб явности. Но я давно не читал наш свежий код, поэтому мой голос можно смело игнорить

**Comment by denisSurkov** [comment]
@f213 ,

> Мне оба варианта не нравятся — кажется мы не пишем настолько много сервисов, чтобы экономить строчку кода в ущерб явности.

Проблема сейчас, что единственная точка входа - act(). Если на нее вешают @transaction.atomic, то самим сервисом не предусмотрено, чтобы как-то выполнить действие после транзакции.

Выходит, что у нас есть сервис ```UserImporter()```, а после него нужно вызывать ```download_user_photo(user.id)```. Хочется держать это все в рамках одного сервиса.

**Comment by kazqvaizer** [comment]
@denisSurkov для этой задачи обычно используется on_commit https://docs.djangoproject.com/en/4.0/topics/db/transactions/#django.db.transaction.on_commit

Я использовал с таким декоратором для тестов
```
def on_transaction_commit(fn):
    """Creates callback that will be executed when current transaction
    will be successfully committed.

    Helps when you need to start a celery task after some object creation
    in transaction.
    """

    @wraps(fn)
    def wrapped(*args, **kwargs):
        if settings.ON_COMMIT_ALWAYS_EAGER:
            fn(*args, **kwargs)
        else:
            transaction.on_commit(lambda: fn(*args, **kwargs))

    return wrapped
```

**Comment by denisSurkov** [comment]
@kazqvaizer , 

> для этой задачи обычно используется on_commit

выходит, что transaction.on_commit это не глобальный хук, а привязано только к контекстной транзакции (with transaction.atomic, что и делает декоратор)?


> Я использовал с таким декоратором для тестов

про декоратор не совсем понял. Можешь показать, как его заюзать для таски? Флаг ALWAYS_EAGER понимаю. Декоратором оборачивать метод сервиса?

```python
...
   @transaction.atomic
   def act(self):
          model = self.create_model()
          self.send_notification(model)

    @on_transaction_commit
    def send_notification(self, model):
           send_user_notification.delay(model.user_id)
...
```
?

**Comment by kazqvaizer** [comment]
>  transaction.on_commit это не глобальный хук,

Если я правильно понял вопрос, то on_commit работает для всех транзакций, начатых и незаконченных до этой строчки. Например, у тебя может стоять глобальная настройка в джанге [ATOMIC_REQUEST](https://docs.djangoproject.com/en/4.1/ref/settings/#std-setting-DATABASE-ATOMIC_REQUESTS) т.е. в коде явно нигде не ставят atomic, а все равно есть транзакция. Поэтому on_commit будет работать.

on_commit хорош еще тем, что мы в вебиуме практикуем вызов одних сервисов внутри других сервисов. Т.е. [твое](https://github.com/fandsdev/django/issues/519#issue-1328153925) предложение не сработает, если ошибка произойдет в сервисе выше. on_comiit убережет от такого: 

```
@atomic
def act(huelf):
   UnoService()()  # <-- запустит селери таску
   DosServce()()   # <-- тут ошибка. Не надо было запускать селери, но уже поздно
```

> Декоратором оборачивать метод сервиса

Да, именно так

**Comment by denisSurkov** [comment]
@kazqvaizer , спасибо!

выглядит круто, заюзаю `transaction.on_commit` вместо изменения класса сервиса.
