### ISSUE TITLE
Обновить на Django >= 4.0 & python3.10

### ISSUE THREAD

**Issue by denisSurkov** [fandsdev/django#521]
Во внутренних проектах используется python3.10. Предлагаю зафиксировать это в [readme.md](https://github.com/fandsdev/django/blob/1aefcc4dccc89bbab7a53c66308454756bac65f9/%7B%7Bcookiecutter.project_slug%7D%7D/README.md?plain=1#L16).

Django 4.0 спорный момент. Я пока не трогал асинхронную джангу. Но если джанга движется туда, а значит это тренд. 

https://www.djangoproject.com/weblog/2021/dec/07/django-40-released/
https://docs.djangoproject.com/en/4.1/topics/async/

@f213 , @kazqvaizer , @nvo87 , @e-stepanov, что думаете о Django 4?

**Comment by f213** [comment]
Зафиксировать минимальную версию питона — я только за. А вот уход с LTS-джанги меня немного смущает. У нас есть понимание, ради каких фич мы это делаем?

Я бы как минимум потыкал 4.1 где-нибудь на живом проекте, прежде чем затаскивать в стартер.

**Comment by f213** [comment]
Кста, если будем фиксировать версию питона, нужно что-то сделать с ворнингами, которые продьюсит pytest-freezegun на питоне 3.10, типа как [тут](https://github.com/tough-dev-school/education-backend/commit/228e21d5649acbc18fcd07d11acf76c7f6581706)

**Comment by denisSurkov** [comment]
пока не попробуем 4 джангу в бою, шаблон не меняем
версию питона обновил, issue закрываю
